[project]
authors = ["Dennis <dennis.kovarik@protonmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "Graph_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.2.0,<26"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
numpy = ">=1.26.4,<2"
ipython = ">=8.31.0,<9"
tqdm = ">=4.67.1,<5"
graph = ">=1.11,<2"
matplotlib = ">=3.10.1,<4"
