[project]
authors = ["Dennis <dennis.kovarik@protonmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "Graph_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
numpy = ">=1.26.4,<2"
